#!/bin/sh

ETCDIR=/mnt/data/etc/framegrabber/
WEBSOCKET_MAINSTREAM_PIPE="${ETCDIR}websocket_mainstream"

mkdir -p $ETCDIR
mkfifo $WEBSOCKET_MAINSTREAM_PIPE

cd /mnt/sdcard/hacks/framegrabber/bin
exec ./framegrabber -f $WEBSOCKET_MAINSTREAM_PIPE -c 0