#!/bin/sh

ETCDIR=/mnt/data/etc/framegrabber/
WEBSOCKET_SUBSTREAM_PIPE="${ETCDIR}websocket_substream"

mkdir -p $ETCDIR
mkfifo $WEBSOCKET_SUBSTREAM_PIPE

cd /mnt/sdcard/hacks/framegrabber/bin
exec ./framegrabber -f $WEBSOCKET_SUBSTREAM_PIPE -c 1