#!/bin/sh

ETCDIR=/mnt/data/etc/framegrabber/
RTSP_SUBSTREAM_PIPE="${ETCDIR}rtsp_substream"

mkdir -p $ETCDIR
mkfifo $RTSP_SUBSTREAM_PIPE

cd /mnt/sdcard/hacks/framegrabber/bin
exec ./framegrabber -f $RTSP_SUBSTREAM_PIPE -c 1